name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # NOTE: replace `markdown-link-check` with <https://github.com/UmbrellaDocs/linkspector> when
  # Github Action is available.
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: main
          use-quiet-mode: "yes"
          check-modified-files-only: "yes"
          config-file: "check-markdown-links-config.json"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
